export const products = [
    {
      id: 1,
      name: "Oppo Smartphone",
      image: "https://m.media-amazon.com/images/I/4133ecp7zKL._SX300_SY300_QL70_FMwebp_.jpg",
      description: "XYZ Brand, 6.5-inch AMOLED display, 128GB storage, 5G support.",
      shortDescription: "XYZ Brand, 6.5-inch AMOLED display, 128GB storage.",
      price: "500",
    },
    {
      id: 2,
      name: "Lenovo Laptop",
      image: "https://tse3.mm.bing.net/th?id=OIP.y6MPyepeDGuGjECUb_ztcQHaHa&w=474&h=474&c=7",
      description: "Lenovo, 15.6-inch FHD display, Intel i7, 16GB RAM, 512GB SSD.",
      shortDescription: "Lenovo, 15.6-inch FHD display, Intel i7.",
      price: "1000",
    },
    {
      id: 3,
      name: "Sony Headphones",
      image: "https://m.media-amazon.com/images/I/51l80KVua0L._AC_UY327_FMwebp_QL65_.jpg",
      description: "Sony, Over-ear, Active Noise Cancellation, Bluetooth 5.0.",
      shortDescription: "Sony, Over-ear, Active Noise Cancellation.",
      price: "150",
    },
    {
      id: 21,
      name: "Apple Smartwatch",
      image: "https://m.media-amazon.com/images/I/51ck61uH-GL._AC_UY327_FMwebp_QL65_.jpg",
      description: "Apple, 1.4-inch AMOLED display, Heart rate & SpO2 monitor.",
      shortDescription: "Apple, 1.4-inch AMOLED display.",
      price: "250",
    },
    {
      id: 5,
      name: "Nintendo Gaming Console",
      image: "https://m.media-amazon.com/images/I/91Tbd4wesvL._AC_UY327_FMwebp_QL65_.jpg",
      description: "Nintendo, 4K Ultra HD gaming, 1TB storage, VR compatibility.",
      shortDescription: "Nintendo, 4K Ultra HD gaming, 1TB storage.",
      price: "400",
    },
    {
      id: 6,
      name: "Canon Camera",
      image: "https://m.media-amazon.com/images/I/3188xYXJQjL._SX300_SY300_QL70_FMwebp_.jpg",
      description: "Canon, 24.2MP sensor, 4K video recording, 18-55mm lens.",
      shortDescription: "Canon, 24.2MP sensor, 4K video recording.",
      price: "700",
    },
    {
      id: 7,
      name: "JBL Bluetooth Speaker",
      image: "https://tse1.mm.bing.net/th?id=OIP.c0xMX1PfyE4fPzWVondLwAHaG-&w=446&h=446&c=7",
      description: "JBL, 20W output, IPX7 waterproof, 12-hour battery life.",
      shortDescription: "JBL, 20W output, IPX7 waterproof.",
      price: "100",
    },
    {
      id: 8,
      name: "Samsung Tablet",
      image: "https://tse1.mm.bing.net/th?id=OIP.Zk8F5CI1UKocMt2ZHM2EqAHaHa&w=474&h=474&c=7",
      description: "Samsung, 10.4-inch LCD, 64GB storage, Wi-Fi + LTE.",
      shortDescription: "Samsung, 10.4-inch LCD, 64GB storage.",
      price: "300",
    },
    {
      id: 117,
      name: "Women's Leggings",
      image: "https://m.media-amazon.com/images/I/51mzvI1WENL._SY741_.jpg",
      description: "High-waist leggings, stretchable fabric, perfect for workouts.",
      shortDescription: "High-waist stretchable leggings.",
      price: "35",
  },
  {
      id: 118,
      name: "Men's Sunglasses",
      image: "https://tse1.mm.bing.net/th?id=OIP.VpPwQzMezgxSthNaIXaXCAHaJ4&w=474&h=474&c=7",
      description: "Polarized aviators with a lightweight frame, UV protection.",
      shortDescription: "Polarized aviator sunglasses.",
      price: "50",
  },
  {
      id: 119,
      name: "Women's Fashion Necklace",
      image: "https://m.media-amazon.com/images/I/61AO5S0R6fL._AC_UL480_FMwebp_QL65_.jpg",
      description: "Statement necklace with cubic zirconia, gold-plated chain.",
      shortDescription: "Gold-plated statement necklace.",
      price: "65",
  },
  {
      id: 120,
      name: "Unisex Backpack",
      image: "https://m.media-amazon.com/images/I/61au90efRKL._AC_UY327_FMwebp_QL65_.jpg",
      description: "Durable backpack with multiple compartments, laptop sleeve included.",
      shortDescription: "Durable backpack with laptop sleeve.",
      price: "70",
  },
    {
      id: 9,
      name: "Garmin Fitness Band",
      image: "https://picsum.photos/200/300?random=9",
      description: "Garmin, AMOLED display, Step & sleep tracker, 10-day battery.",
      shortDescription: "Garmin, AMOLED display, Step tracker.",
      price: "50",
    },
    {
      id: 10,
      name: "Logitech Wireless Keyboard",
      image: "https://picsum.photos/200/300?random=10",
      description: "Logitech, Compact design, Bluetooth & USB, Silent keys.",
      shortDescription: "Logitech, Compact design, Bluetooth & USB.",
      price: "80",
    },
    {
      id: 11,
      name: "HP Pavilion Laptop",
      image: "https://picsum.photos/200/300?random=11",
      description: "HP Pavilion, 14-inch Full HD, Intel i5, 8GB RAM, 256GB SSD.",
      shortDescription: "HP Pavilion, 14-inch Full HD, Intel i5.",
      price: "750",
    },
    {
      id: 12,
      name: "Apple MacBook Pro",
      image: "https://picsum.photos/200/300?random=12",
      description: "Apple, 13-inch Retina display, Intel i7, 16GB RAM, 512GB SSD.",
      shortDescription: "Apple, 13-inch Retina display, Intel i7.",
      price: "1800",
    },
    {
      id: 13,
      name: "Samsung Galaxy Watch",
      image: "https://picsum.photos/200/300?random=13",
      description: "Samsung, 1.5-inch AMOLED display, Fitness & health tracking.",
      shortDescription: "Samsung, 1.5-inch AMOLED display.",
      price: "220",
    },
    {
      id: 14,
      name: "Asus ROG Gaming Laptop",
      image: "https://picsum.photos/200/300?random=14",
      description: "Asus, 15.6-inch 4K, Intel i9, 32GB RAM, 1TB SSD, Nvidia RTX 3070.",
      shortDescription: "Asus, 15.6-inch 4K, Intel i9.",
      price: "2500",
    },
    {
      id: 15,
      name: "Fitbit Charge 5 Fitness Tracker",
      image: "https://picsum.photos/200/300?random=15",
      description: "Fitbit, AMOLED display, Built-in GPS, Heart rate monitoring.",
      shortDescription: "Fitbit, AMOLED display, Built-in GPS.",
      price: "150",
    },
    {
      id: 16,
      name: "Bose QuietComfort 35 II Headphones",
      image: "https://picsum.photos/200/300?random=16",
      description: "Bose, Over-ear, Noise-cancelling, Bluetooth 5.0.",
      shortDescription: "Bose, Over-ear, Noise-cancelling.",
      price: "300",
    },
    {
      id: 17,
      name: "Microsoft Surface Laptop",
      image: "https://picsum.photos/200/300?random=17",
      description: "Microsoft, 13.5-inch PixelSense display, Intel i5, 8GB RAM, 256GB SSD.",
      shortDescription: "Microsoft, 13.5-inch PixelSense display.",
      price: "1300",
    },
    {
      id: 18,
      name: "Sony Alpha A7 III Camera",
      image: "https://picsum.photos/200/300?random=18",
      description: "Sony, 24.2MP, Full-frame, 4K video, 28-70mm lens.",
      shortDescription: "Sony, 24.2MP, Full-frame, 4K video.",
      price: "2200",
    },
    {
      id: 19,
      name: "Dell XPS 13 Laptop",
      image: "https://picsum.photos/200/300?random=19",
      description: "Dell, 13.3-inch FHD, Intel i7, 16GB RAM, 512GB SSD.",
      shortDescription: "Dell, 13.3-inch FHD, Intel i7.",
      price: "1500",
    },
    {
      id: 20,
      name: "Oculus Quest 2 VR Headset",
      image: "https://picsum.photos/200/300?random=20",
      description: "Oculus, 64GB storage, Wireless, VR Experience.",
      shortDescription: "Oculus, 64GB storage, Wireless.",
      price: "299",
    },
    // Repeat similar structures for other product entries up to 100 products
    {
      id: 4,
      name: "Samsung Galaxy Buds Pro",
      image: "https://picsum.photos/200/300?random=21",
      description: "Samsung, True wireless earbuds, Active Noise Cancellation.",
      shortDescription: "Samsung, True wireless earbuds.",
      price: "199",
    },
    // Add more entries in the same way for a total of 100 products
    {
      id: 101,
      name: "Men's Leather Jacket",
      image: "https://picsum.photos/200/300?random=101",
      description: "Genuine leather jacket, slim fit, available in black and brown.",
      shortDescription: "Genuine leather jacket, slim fit.",
      price: "150",
  },
  {
      id: 102,
      name: "Women's Silk Scarf",
      image: "https://picsum.photos/200/300?random=102",
      description: "100% silk scarf, hand-painted floral design, 70x70 cm.",
      shortDescription: "100% silk scarf, floral design.",
      price: "45",
  },
  {
      id: 103,
      name: "Unisex Aviator Sunglasses",
      image: "https://picsum.photos/200/300?random=103",
      description: "Polarized lenses, UV400 protection, sleek metallic frame.",
      shortDescription: "Polarized lenses, metallic frame.",
      price: "60",
  },
  {
      id: 104,
      name: "Luxury Chronograph Watch",
      image: "https://picsum.photos/200/300?random=104",
      description: "Stainless steel strap, water-resistant up to 50m, multiple dials.",
      shortDescription: "Stainless steel, water-resistant.",
      price: "250",
  },
  {
      id: 105,
      name: "Men's Sneakers",
      image: "https://picsum.photos/200/300?random=105",
      description: "Comfortable running shoes with a breathable mesh design.",
      shortDescription: "Breathable running shoes.",
      price: "100",
  },
  {
      id: 106,
      name: "Women's Evening Gown",
      image: "https://picsum.photos/200/300?random=106",
      description: "Full-length gown, sequined bodice, available in multiple colors.",
      shortDescription: "Full-length sequined gown.",
      price: "180",
  },
  {
      id: 107,
      name: "Designer Handbag",
      image: "https://picsum.photos/200/300?random=107",
      description: "Leather handbag, gold-tone hardware, detachable strap.",
      shortDescription: "Leather handbag with gold-tone hardware.",
      price: "220",
  },
  {
      id: 108,
      name: "Men's Classic Suit",
      image: "https://picsum.photos/200/300?random=108",
      description: "Two-piece suit, slim fit, wool blend, perfect for formal occasions.",
      shortDescription: "Slim fit wool blend suit.",
      price: "300",
  },
  {
      id: 109,
      name: "Women's High Heels",
      image: "https://picsum.photos/200/300?random=109",
      description: "Elegant stilettos with a pointed toe and cushioned sole.",
      shortDescription: "Elegant stilettos, cushioned sole.",
      price: "80",
  },
  {
      id: 110,
      name: "Men's Sports Watch",
      image: "https://picsum.photos/200/300?random=110",
      description: "Digital display, shock-resistant, ideal for outdoor activities.",
      shortDescription: "Digital sports watch, shock-resistant.",
      price: "120",
  },
  {
      id: 111,
      name: "Women's Denim Jacket",
      image: "https://picsum.photos/200/300?random=111",
      description: "Classic blue denim jacket, distressed design, comfortable fit.",
      shortDescription: "Classic distressed denim jacket.",
      price: "75",
  },
  {
      id: 112,
      name: "Men's Leather Belt",
      image: "https://picsum.photos/200/300?random=112",
      description: "High-quality leather belt, adjustable buckle, black and brown options.",
      shortDescription: "High-quality leather belt.",
      price: "30",
  },
  {
      id: 113,
      name: "Women's Tote Bag",
      image: "https://picsum.photos/200/300?random=113",
      description: "Spacious tote bag with multiple compartments, water-resistant material.",
      shortDescription: "Spacious, water-resistant tote bag.",
      price: "55",
  },
  {
      id: 114,
      name: "Men's Formal Shoes",
      image: "https://picsum.photos/200/300?random=114",
      description: "Classic lace-up shoes, genuine leather, anti-slip sole.",
      shortDescription: "Genuine leather formal shoes.",
      price: "95",
  },
  {
      id: 115,
      name: "Women's Summer Hat",
      image: "https://picsum.photos/200/300?random=115",
      description: "Wide-brim hat, woven straw design, UPF 50+ sun protection.",
      shortDescription: "Wide-brim summer hat.",
      price: "40",
  },
  {
      id: 116,
      name: "Men's Hoodie",
      image: "https://picsum.photos/200/300?random=116",
      description: "Casual pullover hoodie, soft cotton blend, kangaroo pocket.",
      shortDescription: "Soft cotton blend hoodie.",
      price: "60",
  },
  {
      id: 117,
      name: "Women's Leggings",
      image: "https://picsum.photos/200/300?random=117",
      description: "High-waist leggings, stretchable fabric, perfect for workouts.",
      shortDescription: "High-waist stretchable leggings.",
      price: "35",
  },
  {
      id: 118,
      name: "Men's Sunglasses",
      image: "https://picsum.photos/200/300?random=118",
      description: "Polarized aviators with a lightweight frame, UV protection.",
      shortDescription: "Polarized aviator sunglasses.",
      price: "50",
  },
  {
      id: 119,
      name: "Women's Fashion Necklace",
      image: "https://picsum.photos/200/300?random=119",
      description: "Statement necklace with cubic zirconia, gold-plated chain.",
      shortDescription: "Gold-plated statement necklace.",
      price: "65",
  },
  {
      id: 120,
      name: "Unisex Backpack",
      image: "https://picsum.photos/200/300?random=120",
      description: "Durable backpack with multiple compartments, laptop sleeve included.",
      shortDescription: "Durable backpack with laptop sleeve.",
      price: "70",
  },
];
  
